"""Descrição da migração

Revision ID: 39755a82aba0
Revises: 11cffa4ed170
Create Date: 2024-07-01 15:54:07.571876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39755a82aba0'
down_revision = '11cffa4ed170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formacao')
    # ### end Alembic commands ###
