"""Add formacao_id to curso

Revision ID: 652b8e2162c5
Revises: 39755a82aba0
Create Date: 2024-07-02 11:15:58.896283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652b8e2162c5'
down_revision = '39755a82aba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curso', sa.Column('formacao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curso', type_='foreignkey')
    op.drop_column('curso', 'formacao_id')
    # ### end Alembic commands ###
